name: flutter_Twitter
description: A Flutter plugin for allowing users to authenticate with native Android &amp; iOS Twitter login SDKs.
version: 1.1.0
author: Golden <golden.venus0610@gmail.com>

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.roughike.fluttertwitterlogin.fluttertwitterlogin
    pluginClass: TwitterLoginPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
